### ISSUE TITLE
[Feature Request] Dynamic Bone Grabbing

### ISSUE THREAD

**Issue by rakosi2** [9E4ECDDE/MultiplayerDynamicBonesMod#2]
emmVRC/emmVRC-Public#1439
This feature may be better suited for MDBM instead of building it into emmVRC

**Comment by 9E4ECDDE** [comment]
For reference this was the feature request
> Add a similar function to that in NeosVR, that can be applied independently of Global Dynamic Bones, so it would only work on your avatar, or it could be global so you could grab anyone's dynamic bones. It should let you grab any scripts within your hand collider radius when you fully press the Trigger on the VR controller. This would allow people to grab their skirts, ears, tails, hair, and so on.

While a neat idea I see a few problems with trying to make grabbable dynamic bones work.

My main concern is that is would be mainly local only and general interaction issues:
   I do not believe there is a way to see another user's trigger state, the closest I know of would be to watch an SDK3 avatar's GestureWeight, but that only applies when doing the fist gesture. Without that detail, it would be impossible to have someone else grab a bone. Also if you do enable global bone grabbing and other users don't have the mod, I would expect to see a lot of unintentional interactions. 

> This would allow people to grab their skirts, ears, tails, hair, and so on.

It is my thought it if someone wants their cute actions to be seen by others, just use the built in colliders on the avatar for the time being.


Also with the recent Dev stream and announcement of Physics bones slated for this "summer" I am less inclined to think this is worth the dev time.

**Comment by rakosi2** [comment]
I agree. Now that we know about Physics bones is coming, it may be better for us to just wait for PB. I will be closing this ticket.
