### ISSUE TITLE
Mod hanging in loading?

### ISSUE THREAD

**Issue by SquidNeko** [9E4ECDDE/MultiplayerDynamicBonesMod#4]
I keep having the issue that this mod stalls VRChat from launching at this line.
[15:30:16.065] [MultiplayerDynamicBonesMod] Loaded - UserData/MDB/BonesToAlwaysExclude.txt

Sometimes it moves past it. But around 70% of the time it gets stuck on that line and VRChat is just a black screen. Removing this mod fixes it.

**Comment by 9E4ECDDE** [comment]
We talked in DMs and the issue was related to ML failing to load MelonPreferences.cfg due to . vs , for a decimal separator, then hanging when MDB tried to save a MelonPref with the import
