### ISSUE TITLE
Colliders stop working after switching avatar

### ISSUE THREAD

**Issue by MrDj200** [9E4ECDDE/MultiplayerDynamicBonesMod#7]
Ever since the new UI update, whenever I switch avatar, I have to disable and then enable MDB colliders for them to work.

There is just no reaction at all right after switching avatar

**Comment by 9E4ECDDE** [comment]
Are you also using the mod "Turbones" with 'Optimized Simulation' enabled? That can cause interaction to stop working after calibration. 
Simply disabling 'Optimized Simulation' fixes that. And most of the performance benefit comes from Optimized collision checks anyway.

**Comment by MrDj200** [comment]
I see. Thanks ^^
